name: Remote Git Pull and Run Playwright Tests

on:
  push:
    branches:
      - main # Trigger for main branch
      - staging # Trigger for staging branch

jobs:
  deploy:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.REMOTE_HOST }} >> ~/.ssh/known_hosts

      - name: SSH into server and perform git pull
        env:
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
        run: |
          ssh $REMOTE_USER@$REMOTE_HOST << EOF
            cd code/evc-tracker
            git pull origin main
          EOF

  run-playwright-tests:
    if: github.ref == 'refs/heads/staging'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          npm install

      - name: Deploy app to staging server
        run: |
          npm run start &

      - name: Wait for the server to start
        run: |
          npx wait-on http://localhost:3000

      - name: Install Playwright browers
        run: |
          npx playwright install --with-deps

      - name: Run Playwright tests
        run: |
          npm run test

      - name: Upload Playwright artifacts
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: playwright-artifacts
          path: playwright-report
